"""
Django settings for firePlanProject project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab

# 时区设置
USE_TZ = True
TIME_ZONE = 'Asia/Shanghai'  # 使用北京时间

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()  # 加载 .env 文件中的环境变量

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_MODE = {
    'release': False,
    'testing': True
}

SERVER_MODE = os.environ.get('SERVER_MODE', 'release')
DEBUG = DEBUG_MODE.get(SERVER_MODE, False)


ALLOWED_HOSTS_LIST = {
    'release': 'api.guizhenintel.com',
    'testing': 'api-testing.guizhenintel.com'
}

ALLOWED_HOST = ALLOWED_HOSTS_LIST[os.environ.get('SERVER_MODE')]


ALLOWED_HOSTS = [ALLOWED_HOST, 'localhost', '127.0.0.1']
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


ROOT_URLCONF = 'firePlanProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'firePlanProject.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
#    'DEFAULT_PERMISSION_CLASSES': [
#        'rest_framework.permissions.IsAuthenticated',
#    ],
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django_extensions',
    'corsheaders',
    'fire_100UpPlan',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]



# ADD JWT 设置
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# PayPal 配置
PAYPAL_MODE = os.environ.get('PAYPAL_MODE')
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID')
PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET')
PAYPAL_WEBHOOK_ID = os.environ.get('PAYPAL_WEBHOOK_ID')

PAYPAL_ENDPOINTS = {
    'sandbox': 'https://api.sandbox.paypal.com',
    'live': 'https://api.paypal.com'
}

PAYPAL_API_BASE = PAYPAL_ENDPOINTS[PAYPAL_MODE]

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# 允许所有来源访问
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "https://api.guizhenintel.com",
    "http://fireqinglv.guizhenintel.com",
    "https://fireqinglv.guizhenintel.com",
    "http://localhost:5666",
    "http://127.0.0.1:5666",
]

# 允许携带凭证（如果需要）
CORS_ALLOW_CREDENTIALS = True

# 允许所有的 HTTP 方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 允许所有的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'connection',
]

CSRF_TRUSTED_ORIGINS_ALLOWED = {
    'release': 'https://api.guizhenintel.com',
    'testing': 'https://api-testing.guizhenintel.com'
}

CSRF_TRUSTED_ORIGINS = [CSRF_TRUSTED_ORIGINS_ALLOWED[os.environ.get('SERVER_MODE')],'chrome-extension://gidgjoelmejkmlngjdmoeemeckhifchl']


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MiniMax API 设置
MINIMAX_GROUP_ID = os.environ.get('MINIMAX_GROUP_ID')
MINIMAX_API_KEY = os.environ.get('MINIMAX_API_KEY')

# Kimi API 设置
KIMI_API_KEY = os.environ.get('KIMI_API_KEY')

# 日志配置
LOG_FILE_PATH = os.environ.get('LOG_FILE_PATH', os.path.join(BASE_DIR, 'logs', 'django_debug.log'))

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS')
# EMAIL_USE_SSL For port 465
# EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')
BCC_EMAIL = os.environ.get('BCC_EMAIL')

# 集思录 API 设置
JISILU_API_COOKIE = os.environ.get('JISILU_API_COOKIE')

# Celery 时区设置
CELERY_TIMEZONE = 'Asia/Shanghai'  # Celery 也使用相同的时区

# Celery 配置
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND')
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery Beat 定时任务配置
CELERY_BEAT_SCHEDULE = {
    'fetch-daily-market-data': {
        'task': 'fire_100UpPlan.tasks.fetch_daily_market_data',
        'schedule': crontab(hour=20, minute=00),  # 每天20:00执行
    },
    'fetch-index-data': {
        'task': 'fire_100UpPlan.tasks.fetch_index_data',
        'schedule': crontab(hour=20, minute=5),  # 每天20:05执行
    },
    'fetch-margin-trading-data': {
        'task': 'fire_100UpPlan.tasks.fetch_margin_trading_data',
        'schedule': crontab(hour=20, minute=10),  # 每天20:10执行
    },
    'fetch-industry-valuation-data': {
        'task': 'fire_100UpPlan.tasks.fetch_industry_valuation_data',
        'schedule': crontab(hour=20, minute=15),  # 每天20:15执行
    },
    'fetch_convertible_bond_data': {
        'task': 'fire_100UpPlan.tasks.fetch_convertible_bond_data',
        'schedule': crontab(hour=20, minute=20),  # 每天20:20执行
    },
    'fetch-bond-index-data': {
        'task': 'fire_100UpPlan.tasks.fetch_bond_index_data',
        'schedule': crontab(hour=20, minute=25),  # 每天20:25执行
    },
    'fetch-bigdata-strategy-data': {
        'task': 'fire_100UpPlan.tasks.fetch_bigdata_strategy_data',
        'schedule': crontab(hour=20, minute=30),  # 每天20:30执行
    },
    'fetch-daily-market-data2': {
        'task': 'fire_100UpPlan.tasks.fetch_daily_market_data',
        'schedule': crontab(hour=20, minute=35),  # 每天20:35执行
    }
}

SITE_ID = int(os.getenv('SITE_ID', 1))

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE_PATH,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# 默认用户组设置
DEFAULT_USER_GROUPS = {
    'NORMAL_USER': 'Basic',
    'VIP_USER': 'Premium',
    'ADMIN_USER': 'Admin'
}


