# Generated by Django 5.1.2 on 2024-12-18 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('type', models.CharField(max_length=50, verbose_name='菜单类型')),
                ('key', models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单key')),
                ('url', models.URLField(blank=True, null=True, verbose_name='跳转链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_buttons', to='weixin_offiaccount.wechatmenu')),
            ],
            options={
                'verbose_name': '微信菜单',
                'verbose_name_plural': '微信菜单',
                'ordering': ['order'],
            },
        ),
    ]
