# Generated by Django 5.1.2 on 2025-01-08 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_offiaccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatmenu',
            name='appid',
            field=models.CharField(blank=True, help_text='小程序的appid（仅认证公众号可配置）', max_length=100, null=True, verbose_name='小程序APPID'),
        ),
        migrations.AddField(
            model_name='wechatmenu',
            name='article_id',
            field=models.CharField(blank=True, help_text='发布后获得的合法 article_id', max_length=100, null=True, verbose_name='文章ID'),
        ),
        migrations.AddField(
            model_name='wechatmenu',
            name='media_id',
            field=models.CharField(blank=True, help_text='调用新增永久素材接口返回的合法media_id', max_length=100, null=True, verbose_name='素材ID'),
        ),
        migrations.AddField(
            model_name='wechatmenu',
            name='pagepath',
            field=models.CharField(blank=True, help_text='小程序的页面路径', max_length=200, null=True, verbose_name='小程序页面路径'),
        ),
        migrations.AlterField(
            model_name='wechatmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_buttons', to='weixin_offiaccount.wechatmenu', verbose_name='父级菜单'),
        ),
        migrations.AlterField(
            model_name='wechatmenu',
            name='type',
            field=models.CharField(choices=[('view', '网页类型'), ('click', '点击类型'), ('miniprogram', '小程序类型'), ('scancode_push', '扫码访问'), ('scancode_waitmsg', '扫码带提示'), ('pic_sysphoto', '系统拍照发图'), ('pic_photo_or_album', '拍照或相册发图'), ('pic_weixin', '微信相册发图'), ('location_select', '地理位置选择'), ('article_id', '图文id'), ('article_view_limited', '图文消息')], max_length=20, verbose_name='菜单类型'),
        ),
    ]
