# Generated by Django 5.1.2 on 2025-03-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_offiaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信文章',
                'verbose_name_plural': '微信文章',
            },
        ),
    ]
