# Generated by Django 5.1.2 on 2024-12-18 04:27

from django.db import migrations

def migrate_wechat_menu_data(apps, schema_editor):
    # 获取旧的和新的模型
    OldWeChatMenu = apps.get_model('fire_100UpPlan', 'WeChatMenu')
    NewWeChatMenu = apps.get_model('weixin_offiaccount', 'WeChatMenu')
    
    # 迁移数据
    for menu in OldWeChatMenu.objects.all():
        NewWeChatMenu.objects.create(
            name=menu.name,
            type=menu.type,
            key=menu.key,
            url=menu.url,
            parent_id=menu.parent_id,
            order=menu.order,
            updated_at=menu.updated_at
        )

class Migration(migrations.Migration):
    dependencies = [
        ('fire_100UpPlan', '0001_initial'),  # 使用实际的 fire_100UpPlan 迁移文件名
        ('weixin_offiaccount', '0001_initial'),  # 使用实际的 weixin_offiaccount 初始迁移文件名
    ]

    operations = [
        migrations.RunPython(migrate_wechat_menu_data),
    ]
