# Generated by Django 5.1.2 on 2025-03-27 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_offiaccount', '0002_wechatmenu_appid_wechatmenu_article_id_and_more'),
        ('weixin_offiaccount', '0002_weixinarticle'),
    ]

    operations = [
    ]
