# Generated by Django 5.1.2 on 2024-12-18 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_offiaccount', '0002_auto_20241218_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmenu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_buttons', to='weixin_offiaccount.wechatmenu', verbose_name='父级菜单'),
        ),
        migrations.AlterField(
            model_name='wechatmenu',
            name='type',
            field=models.CharField(choices=[('view', '网页类型'), ('click', '点击类型'), ('miniprogram', '小程序类型')], max_length=20, verbose_name='菜单类型'),
        ),
    ]
