# Generated by Django 5.1.2 on 2024-12-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_offiaccount', '0003_alter_wechatmenu_parent_alter_wechatmenu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechatmenu',
            name='appid',
            field=models.CharField(blank=True, help_text='小程序的appid（仅认证公众号可配置）', max_length=100, null=True, verbose_name='小程序APPID'),
        ),
        migrations.AddField(
            model_name='wechatmenu',
            name='article_id',
            field=models.CharField(blank=True, help_text='发布后获得的合法 article_id', max_length=100, null=True, verbose_name='文章ID'),
        ),
        migrations.AddField(
            model_name='wechatmenu',
            name='media_id',
            field=models.CharField(blank=True, help_text='调用新增永久素材接口返回的合法media_id', max_length=100, null=True, verbose_name='素材ID'),
        ),
        migrations.AddField(
            model_name='wechatmenu',
            name='pagepath',
            field=models.CharField(blank=True, help_text='小程序的页面路径', max_length=200, null=True, verbose_name='小程序页面路径'),
        ),
    ]
