# Generated by Django 5.1.2 on 2024-12-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin_offiaccount', '0004_wechatmenu_appid_wechatmenu_article_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmenu',
            name='type',
            field=models.CharField(choices=[('view', '网页类型'), ('click', '点击类型'), ('miniprogram', '小程序类型'), ('scancode_push', '扫码访问'), ('scancode_waitmsg', '扫码带提示'), ('pic_sysphoto', '系统拍照发图'), ('pic_photo_or_album', '拍照或相册发图'), ('pic_weixin', '微信相册发图'), ('location_select', '地理位置选择'), ('article_id', '图文id'), ('article_view_limited', '图文消息')], max_length=20, verbose_name='菜单类型'),
        ),
    ]
