# Generated by Django 5.1.2 on 2024-11-16 08:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('has_basic_features', models.BooleanField(default=True)),
                ('has_advanced_features', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BondData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('yield_rate', models.FloatField(verbose_name='到期收益率')),
                ('duration', models.FloatField(verbose_name='久期')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.FloatField(verbose_name='成交额')),
                ('bond_size', models.FloatField(verbose_name='债券规模')),
                ('is_callable', models.BooleanField(verbose_name='是否强赎')),
                ('industry', models.CharField(max_length=100, null=True, verbose_name='所属行业')),
            ],
            options={
                'db_table': 'market_bond_data',
                'unique_together': {('date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('nav', models.FloatField(verbose_name='净值')),
                ('acc_nav', models.FloatField(verbose_name='累计净值')),
                ('daily_return', models.FloatField(verbose_name='日收益率')),
                ('type', models.CharField(max_length=50, verbose_name='基金类型')),
            ],
            options={
                'db_table': 'market_fund_data',
                'unique_together': {('date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='IndexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('open', models.FloatField(verbose_name='开盘点位')),
                ('high', models.FloatField(verbose_name='最高点位')),
                ('low', models.FloatField(verbose_name='最低点位')),
                ('close', models.FloatField(verbose_name='收盘点位')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.FloatField(verbose_name='成交额')),
                ('pe_ratio', models.FloatField(null=True, verbose_name='市盈率')),
                ('pb_ratio', models.FloatField(null=True, verbose_name='市净率')),
                ('percentile', models.FloatField(null=True, verbose_name='百分位')),
            ],
            options={
                'db_table': 'market_index_data',
                'unique_together': {('date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MarginTradingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('margin_balance', models.FloatField(help_text='单位: 亿', verbose_name='融资余额')),
                ('securities_balance', models.FloatField(help_text='单位: 亿', verbose_name='融券余额')),
                ('margin_buy', models.FloatField(help_text='单位: 亿', verbose_name='融资买入额')),
                ('securities_sell', models.FloatField(help_text='单位: 亿', verbose_name='融券卖出额')),
                ('securities_firms', models.FloatField(help_text='单位: 家', verbose_name='证券公司数量')),
                ('branches', models.FloatField(help_text='单位: 家', verbose_name='营业部数量')),
                ('individual_investors', models.FloatField(help_text='单位: 万名', verbose_name='个人投资者数量')),
                ('institutional_investors', models.FloatField(help_text='单位: 家', verbose_name='机构投资者数量')),
                ('active_traders', models.FloatField(help_text='单位: 名', verbose_name='参与交易的投资者数量')),
                ('margin_traders', models.FloatField(help_text='单位: 名', verbose_name='有融资融券负债的投资者数量')),
                ('collateral_value', models.FloatField(help_text='单位: 亿', verbose_name='担保物总价值')),
                ('maintenance_ratio', models.FloatField(help_text='单位: %', verbose_name='平均维持担保比例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '两融数据',
                'verbose_name_plural': '两融数据',
                'db_table': 'margin_trading_data',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='MarketValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('sector_name', models.CharField(default='沪深市场', max_length=50, verbose_name='板块名称')),
                ('pe_ratio', models.FloatField(null=True, verbose_name='静态市盈率')),
                ('dynamic_pe_ratio', models.FloatField(null=True, verbose_name='滚动市盈率')),
                ('pb_ratio', models.FloatField(null=True, verbose_name='市净率')),
                ('dividend_ratio', models.FloatField(null=True, verbose_name='股息率')),
                ('stock_count', models.IntegerField(null=True, verbose_name='股票家数')),
                ('total_volume', models.FloatField(null=True, verbose_name='全市场交易量')),
                ('total_amount', models.FloatField(null=True, verbose_name='全市场成交额')),
                ('sh_index', models.FloatField(null=True, verbose_name='上证指数')),
                ('sh_pe_rank_percentile', models.FloatField(null=True, verbose_name='上证PE百分位')),
                ('sh_pb_rank_percentile', models.FloatField(null=True, verbose_name='上证PB百分位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'market_valuation',
                'indexes': [models.Index(fields=['date'], name='market_valu_date_1eed49_idx'), models.Index(fields=['sector_name'], name='market_valu_sector__06158f_idx')],
                'unique_together': {('date', 'sector_name')},
            },
        ),
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PENDING', '待处理'), ('COMPLETED', '已完成'), ('REFUNDED', '已退款'), ('REFUND_PENDING', '退款待处理'), ('FAILED', '失败')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_100UpPlan.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fire_100UpPlan.membershippurchase')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fire_100UpPlan.membershiptype')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('high', models.FloatField(verbose_name='最高价')),
                ('low', models.FloatField(verbose_name='最低价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.FloatField(verbose_name='成交额')),
                ('turnover', models.FloatField(null=True, verbose_name='换手率')),
                ('pe_ratio', models.FloatField(null=True, verbose_name='市盈率')),
                ('pb_ratio', models.FloatField(null=True, verbose_name='市净率')),
                ('industry', models.CharField(max_length=100, null=True, verbose_name='所属行业')),
            ],
            options={
                'db_table': 'market_stock_data',
                'unique_together': {('date', 'code')},
            },
        ),
    ]
