# Generated by Django 5.1.2 on 2024-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('industry_code', models.CharField(max_length=10, verbose_name='行业代码')),
                ('industry_name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('static_pe', models.FloatField(null=True, verbose_name='静态市盈率')),
                ('dynamic_pe', models.FloatField(null=True, verbose_name='滚动市盈率')),
                ('pb_ratio', models.FloatField(null=True, verbose_name='市净率')),
                ('dividend_ratio', models.FloatField(null=True, verbose_name='股息率')),
                ('stock_count', models.IntegerField(verbose_name='股票家数')),
                ('parent_industry', models.CharField(max_length=100, null=True, verbose_name='父级行业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'industry_valuation',
                'indexes': [models.Index(fields=['date'], name='industry_va_date_412bd5_idx'), models.Index(fields=['industry_code'], name='industry_va_industr_d1b69f_idx'), models.Index(fields=['parent_industry'], name='industry_va_parent__78e1e0_idx')],
                'unique_together': {('date', 'industry_code')},
            },
        ),
    ]
