# Generated by Django 4.2.16 on 2024-09-14 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import datetime

def create_membership_types(apps, schema_editor):
    MembershipType = apps.get_model('fire_100UpPlan', 'MembershipType')
    MembershipType.objects.create(name="Free User", duration_days=0, has_basic_features=False, has_advanced_features=False, price=0)
    MembershipType.objects.create(name="Trial", duration_days=3, has_basic_features=True, has_advanced_features=True, price=0)
    MembershipType.objects.create(name="Basic Monthly", duration_days=30, has_basic_features=True, has_advanced_features=False, price=9.99)
    MembershipType.objects.create(name="Premium Monthly", duration_days=30, has_basic_features=True, has_advanced_features=True, price=19.99)

def set_end_dates(apps, schema_editor):
    Membership = apps.get_model('fire_100UpPlan', 'Membership')
    for membership in Membership.objects.all():
        if not membership.end_date:
            membership.end_date = membership.start_date + datetime.timedelta(days=membership.membership_type.duration_days)
            membership.save()

def combined_operation(apps, schema_editor):
    create_membership_types(apps, schema_editor)
    set_end_dates(apps, schema_editor)

def reverse_func(apps, schema_editor):
    MembershipType = apps.get_model('fire_100UpPlan', 'MembershipType')
    MembershipType.objects.filter(name__in=["Trial", "Basic Monthly", "Premium Monthly"]).delete()
    # Note: We don't reverse the set_end_dates operation as it might cause data loss

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fire_100UpPlan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('has_basic_features', models.BooleanField(default=True)),
                ('has_advanced_features', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='membership',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='membership',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MembershipPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=20)),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fire_100UpPlan.membershiptype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fire_100UpPlan.membershiptype'),
        ),
        migrations.RunPython(combined_operation, reverse_func),
    ]