# Generated by Django 5.1.2 on 2024-11-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0002_industryvaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexdata',
            name='dynamic_pe_ratio',
            field=models.FloatField(null=True, verbose_name='滚动市盈率'),
        ),
    ]
