# Generated by Django 5.1.2 on 2024-10-31 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0002_create_membership_types_and_set_end_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fire_100UpPlan.membershippurchase'),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='refund_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippurchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_100UpPlan.membershiptype'),
        ),
        migrations.AlterField(
            model_name='membershippurchase',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('COMPLETED', '已完成'), ('REFUNDED', '已退款'), ('REFUND_PENDING', '退款待处理'), ('FAILED', '失败')], default='PENDING', max_length=20),
        ),
    ]
