# Generated by Django 5.1.2 on 2024-11-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0003_indexdata_dynamic_pe_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdata',
            name='amount',
            field=models.FloatField(null=True, verbose_name='成交额'),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='close',
            field=models.FloatField(null=True, verbose_name='收盘点位'),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='high',
            field=models.FloatField(null=True, verbose_name='最高点位'),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='low',
            field=models.FloatField(null=True, verbose_name='最低点位'),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='open',
            field=models.FloatField(null=True, verbose_name='开盘点位'),
        ),
        migrations.AlterField(
            model_name='indexdata',
            name='volume',
            field=models.BigIntegerField(null=True, verbose_name='成交量'),
        ),
    ]
