# Generated by Django 5.1.2 on 2024-11-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0004_alter_indexdata_amount_alter_indexdata_close_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvaluation',
            name='pb_range_percentile',
            field=models.FloatField(null=True, verbose_name='PB区间百分位'),
        ),
        migrations.AddField(
            model_name='marketvaluation',
            name='pe_range_percentile',
            field=models.FloatField(null=True, verbose_name='PE区间百分位'),
        ),
    ]
