# Generated by Django 5.1.2 on 2024-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0005_marketvaluation_pb_range_percentile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonddata',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='yield_rate',
        ),
        migrations.AddField(
            model_name='bonddata',
            name='bond_rating',
            field=models.CharField(max_length=50, null=True, verbose_name='债券评级'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='buyback_price',
            field=models.FloatField(null=True, verbose_name='回售触发价'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='convertible_price',
            field=models.FloatField(null=True, verbose_name='转股价'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='convertible_ratio',
            field=models.FloatField(null=True, verbose_name='转债占比'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='convertible_start_date',
            field=models.DateField(null=True, verbose_name='转股起始日'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='convertible_value',
            field=models.FloatField(null=True, verbose_name='转股价值'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='double_low',
            field=models.FloatField(null=True, verbose_name='双低'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='last_trading_date',
            field=models.DateField(null=True, verbose_name='最后交易日'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='maturity_date',
            field=models.DateField(null=True, verbose_name='到期时间'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='premium_rate',
            field=models.FloatField(null=True, verbose_name='转股溢价率'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='redemption_price',
            field=models.FloatField(null=True, verbose_name='强赎价格'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='redemption_trigger_price',
            field=models.FloatField(null=True, verbose_name='强赎触发价'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='remaining_size',
            field=models.FloatField(null=True, verbose_name='剩余规模'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='remaining_years',
            field=models.FloatField(null=True, verbose_name='剩余年限'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_code',
            field=models.CharField(max_length=50, null=True, verbose_name='正股代码'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_name',
            field=models.CharField(max_length=100, null=True, verbose_name='正股名称'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_pb',
            field=models.FloatField(null=True, verbose_name='正股PB'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_price',
            field=models.FloatField(null=True, verbose_name='正股价'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='turnover_rate',
            field=models.FloatField(null=True, verbose_name='换手率'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='ytm_before_tax',
            field=models.FloatField(null=True, verbose_name='到期税前收益'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='is_callable',
            field=models.CharField(max_length=50, null=True, verbose_name='强赎状态'),
        ),
    ]
