# Generated by Django 5.1.2 on 2024-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0006_remove_bonddata_duration_remove_bonddata_volume_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonddata',
            options={'verbose_name': '可转债数据', 'verbose_name_plural': '可转债数据'},
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='bond_size',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='buyback_price',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='convertible_ratio',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='industry',
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='amount',
            field=models.FloatField(null=True, verbose_name='成交额'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='close',
            field=models.FloatField(verbose_name='现价'),
        ),
    ]
