# Generated by Django 5.1.2 on 2024-11-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0007_alter_bonddata_options_remove_bonddata_bond_size_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bonddata',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='bonddata',
            index=models.Index(fields=['code'], name='market_bond_code_ea3079_idx'),
        ),
        migrations.AddIndex(
            model_name='bonddata',
            index=models.Index(fields=['date'], name='market_bond_date_1e11b9_idx'),
        ),
    ]
