# Generated by Django 5.1.2 on 2024-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0008_alter_bonddata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexdata',
            options={'verbose_name': '指数数据', 'verbose_name_plural': '指数数据'},
        ),
        migrations.AlterModelOptions(
            name='industryvaluation',
            options={'verbose_name': '行业估值', 'verbose_name_plural': '行业估值'},
        ),
        migrations.AlterModelOptions(
            name='marketvaluation',
            options={'verbose_name': '市场整体估值', 'verbose_name_plural': '市场整体估值'},
        ),
        migrations.CreateModel(
            name='BondIndexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('price', models.FloatField(null=True, verbose_name='指数')),
                ('increase_rt', models.FloatField(null=True, verbose_name='涨幅')),
                ('avg_price', models.FloatField(null=True, verbose_name='平均价格(元)')),
                ('mid_price', models.FloatField(null=True, verbose_name='中位数价格(元)')),
                ('avg_premium_rt', models.FloatField(null=True, verbose_name='平均溢价率')),
                ('mid_premium_rt', models.FloatField(null=True, verbose_name='中位数溢价率')),
                ('avg_ytm_rt', models.FloatField(null=True, verbose_name='平均收益率')),
                ('price_90', models.IntegerField(null=True, verbose_name='>90')),
                ('price_90_100', models.IntegerField(null=True, verbose_name='90~100')),
                ('price_100_110', models.IntegerField(null=True, verbose_name='100~110')),
                ('price_110_120', models.IntegerField(null=True, verbose_name='110~120')),
                ('price_120_130', models.IntegerField(null=True, verbose_name='120~130')),
                ('price_130', models.IntegerField(null=True, verbose_name='>130')),
            ],
            options={
                'verbose_name': '可转债指数',
                'verbose_name_plural': '可转债指数',
                'db_table': 'market_bond_index_data',
                'unique_together': {('date', 'code')},
            },
        ),
    ]
