# Generated by Django 5.1.2 on 2024-11-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0009_alter_indexdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonddata',
            name='redemption_countdown',
            field=models.CharField(max_length=50, null=True, verbose_name='强赎倒计时'),
        ),
    ]
