# Generated by Django 5.1.2 on 2024-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0010_bonddata_redemption_countdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonddata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='remaining_years',
        ),
        migrations.RemoveField(
            model_name='bonddata',
            name='turnover_rate',
        ),
        migrations.AddField(
            model_name='bonddata',
            name='issue_size',
            field=models.FloatField(null=True, verbose_name='发行规模'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='listing_date',
            field=models.DateField(null=True, verbose_name='上市时间'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='subscription_announcement_date',
            field=models.DateField(null=True, verbose_name='中签号发布日'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='subscription_code',
            field=models.CharField(max_length=50, null=True, verbose_name='申购代码'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='subscription_date',
            field=models.DateField(null=True, verbose_name='申购日期'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='subscription_per_share',
            field=models.FloatField(null=True, verbose_name='原股东配售-每股配售额'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='subscription_rate',
            field=models.FloatField(null=True, verbose_name='中签率'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='subscription_record_date',
            field=models.DateField(null=True, verbose_name='原股东配售-股权登记日'),
        ),
    ]
