# Generated by Django 5.1.2 on 2024-11-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0011_remove_bonddata_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='industry',
            new_name='industry_name',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='dividend_ratio',
            field=models.FloatField(null=True, verbose_name='股息率'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='dynamic_pe_ratio',
            field=models.FloatField(null=True, verbose_name='滚动市盈率'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='float_market_value',
            field=models.FloatField(null=True, verbose_name='流通市值'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='parent_industry',
            field=models.CharField(max_length=100, null=True, verbose_name='父级行业'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='sixty_day_increase',
            field=models.FloatField(null=True, verbose_name='近60日涨幅'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='total_market_value',
            field=models.FloatField(null=True, verbose_name='总市值'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='year_to_date_increase',
            field=models.FloatField(null=True, verbose_name='今年以来涨幅'),
        ),
    ]
