# Generated by Django 5.1.2 on 2024-11-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0012_rename_industry_stockdata_industry_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={'verbose_name': '股票数据', 'verbose_name_plural': '股票数据'},
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['date', 'code'], name='market_stoc_date_f0828c_idx'),
        ),
    ]
