# Generated by Django 5.1.2 on 2024-12-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0013_alter_stockdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdata',
            old_name='dynamic_pe_ratio',
            new_name='pe_ttm_ratio',
        ),
    ]
