# Generated by Django 5.1.2 on 2024-12-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0014_rename_dynamic_pe_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexdata',
            old_name='dynamic_pe_ratio',
            new_name='pe_ttm_ratio',
        ),
        migrations.RenameField(
            model_name='industryvaluation',
            old_name='dynamic_pe',
            new_name='ttm_pe',
        ),
    ]
