# Generated by Django 5.1.2 on 2024-12-02 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0015_rename_ttm_pe_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketvaluation',
            old_name='dynamic_pe_ratio',
            new_name='pe_ttm_ratio',
        ),
    ]
