# Generated by Django 5.1.2 on 2024-12-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0016_rename_ttm_pe_ratio_markdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='one_year_increase',
            field=models.FloatField(null=True, verbose_name='近一年涨幅'),
        ),
    ]
