# Generated by Django 5.1.2 on 2024-12-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0017_stockdata_one_year_increase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='one_year_increase',
        ),
        migrations.CreateModel(
            name='BigDataStrategyStockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('one_year_min', models.FloatField(null=True, verbose_name='近一年最低价')),
                ('pe_ratio', models.FloatField(null=True, verbose_name='市盈率')),
                ('pe_ttm_ratio', models.FloatField(null=True, verbose_name='滚动市盈率')),
                ('pb_ratio', models.FloatField(null=True, verbose_name='市净率')),
                ('dividend_ratio', models.FloatField(null=True, verbose_name='股息率')),
                ('industry_name', models.CharField(max_length=100, null=True, verbose_name='所属行业')),
                ('parent_industry', models.CharField(max_length=100, null=True, verbose_name='父级行业')),
                ('total_market_value', models.FloatField(null=True, verbose_name='总市值')),
                ('sixty_day_increase', models.FloatField(null=True, verbose_name='近60日涨幅')),
                ('year_to_date_increase', models.FloatField(null=True, verbose_name='今年以来涨幅')),
                ('one_year_increase', models.FloatField(null=True, verbose_name='近一年涨幅')),
                ('bigdata_score', models.FloatField(null=True, verbose_name='大数得分')),
            ],
            options={
                'verbose_name': '大数股票池',
                'verbose_name_plural': '大数股票池',
                'db_table': 'market_bigdata_strategy_stock_data',
                'unique_together': {('date', 'code')},
            },
        ),
    ]
