# Generated by Django 5.1.2 on 2024-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0018_remove_stockdata_one_year_increase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryvaluation',
            name='pb_ratio_is_normal',
            field=models.BooleanField(null=True, verbose_name='PB是否符合正态分布'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='pb_ratio_mean',
            field=models.FloatField(null=True, verbose_name='PB均值'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='pb_ratio_median',
            field=models.FloatField(null=True, verbose_name='PB中位数'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='pb_ratio_percentiles',
            field=models.JSONField(null=True, verbose_name='PB分位数'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='pb_ratio_std',
            field=models.FloatField(null=True, verbose_name='PB标准差'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='ttm_pe_is_normal',
            field=models.BooleanField(null=True, verbose_name='TTM PE是否符合正态分布'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='ttm_pe_mean',
            field=models.FloatField(null=True, verbose_name='TTM PE均值'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='ttm_pe_median',
            field=models.FloatField(null=True, verbose_name='TTM PE中位数'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='ttm_pe_percentiles',
            field=models.JSONField(null=True, verbose_name='TTM PE分位数'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='ttm_pe_std',
            field=models.FloatField(null=True, verbose_name='TTM PE标准差'),
        ),
    ]
