# Generated by Django 5.1.2 on 2024-12-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0019_industryvaluation_pb_ratio_is_normal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industryvaluation',
            name='pb_ratio_min',
            field=models.FloatField(null=True, verbose_name='PB最小值'),
        ),
        migrations.AddField(
            model_name='industryvaluation',
            name='ttm_pe_min',
            field=models.FloatField(null=True, verbose_name='TTM PE最小值'),
        ),
    ]
