# Generated by Django 5.1.2 on 2024-12-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0020_industryvaluation_pb_ratio_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigdatastrategystockdata',
            name='parent_industry',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='parent_industry',
        ),
        migrations.AddField(
            model_name='bigdatastrategystockdata',
            name='industry_code',
            field=models.CharField(max_length=10, null=True, verbose_name='行业代码'),
        ),
        migrations.AddField(
            model_name='bigdatastrategystockdata',
            name='parent_industry_code',
            field=models.CharField(max_length=10, null=True, verbose_name='父级行业代码'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='industry_code',
            field=models.CharField(max_length=10, null=True, verbose_name='行业代码'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='parent_industry_code',
            field=models.CharField(max_length=10, null=True, verbose_name='父级行业代码'),
        ),
    ]
