# Generated by Django 5.1.2 on 2024-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0021_remove_bigdatastrategystockdata_parent_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='parent_industry_pb_ratio_median',
            field=models.FloatField(null=True, verbose_name='父级行业PB中位数'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='parent_industry_pe_ttm_ratio_median',
            field=models.FloatField(null=True, verbose_name='父级行业TTM PE中位数'),
        ),
    ]
