# Generated by Django 5.1.2 on 2024-12-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0022_stockdata_parent_industry_pb_ratio_median_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigdatastrategystockdata',
            name='bigdata_score_method',
            field=models.CharField(max_length=50, null=True, verbose_name='打分方式'),
        ),
    ]
