# Generated by Django 5.1.2 on 2024-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0023_bigdatastrategystockdata_bigdata_score_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funddata',
            options={'verbose_name': '基金数据', 'verbose_name_plural': '基金数据'},
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_industry_pb_ratio_median',
            field=models.FloatField(null=True, verbose_name='行业中位数PB'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_industry_pe_ttm_ratio_median',
            field=models.FloatField(null=True, verbose_name='行业中位数TTM PE'),
        ),
        migrations.AddField(
            model_name='bonddata',
            name='stock_pe_ttm_ratio',
            field=models.FloatField(null=True, verbose_name='正股TTM PE'),
        ),
    ]
