# Generated by Django 5.1.2 on 2024-12-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0024_alter_funddata_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bigdatastrategystockdata',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='bigdatastrategystockdata',
            index=models.Index(fields=['date', 'code'], name='market_bigd_date_517a9c_idx'),
        ),
    ]
