# Generated by Django 5.1.2 on 2024-12-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0025_alter_bigdatastrategystockdata_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvaluation',
            name='pb_rank_percentile',
            field=models.FloatField(null=True, verbose_name='PB Rank百分位'),
        ),
        migrations.AddField(
            model_name='marketvaluation',
            name='pe_rank_percentile',
            field=models.FloatField(null=True, verbose_name='PE Rank百分位'),
        ),
        migrations.AlterField(
            model_name='marketvaluation',
            name='sh_pb_rank_percentile',
            field=models.FloatField(null=True, verbose_name='上证PB Rank百分位'),
        ),
        migrations.AlterField(
            model_name='marketvaluation',
            name='sh_pe_rank_percentile',
            field=models.FloatField(null=True, verbose_name='上证PE Rank百分位'),
        ),
    ]
