# Generated by Django 5.1.2 on 2024-12-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0026_marketvaluation_pb_rank_percentile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketvaluation',
            name='market_temperature',
            field=models.FloatField(null=True, verbose_name='全市场温度'),
        ),
    ]
