# Generated by Django 5.1.2 on 2024-12-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0027_marketvaluation_market_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('type', models.CharField(choices=[('click', '点击'), ('view', '视图')], max_length=20, verbose_name='类型')),
                ('key', models.CharField(blank=True, max_length=128, verbose_name='菜单KEY')),
                ('url', models.URLField(blank=True, verbose_name='跳转链接')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_buttons', to='fire_100UpPlan.wechatmenu')),
            ],
            options={
                'verbose_name': '微信菜单',
                'verbose_name_plural': '微信菜单',
                'ordering': ['order'],
            },
        ),
    ]
