# Generated by Django 5.1.2 on 2024-12-18 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0028_wechatmenu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeChatMenu',
        ),
    ]
