# Generated by Django 5.1.2 on 2025-01-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0029_auto_20241218_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonddata',
            name='is_risk_excluded',
            field=models.BooleanField(default=False, verbose_name='手动排除'),
        ),
    ]
