# Generated by Django 5.1.2 on 2025-01-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0030_bonddata_is_risk_excluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonddata',
            name='convertible_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='转股起始日'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='is_callable',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='强赎状态'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='last_trading_date',
            field=models.DateField(blank=True, null=True, verbose_name='最后交易日'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='redemption_countdown',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='强赎倒计时'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='redemption_price',
            field=models.FloatField(blank=True, null=True, verbose_name='强赎价格'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='redemption_trigger_price',
            field=models.FloatField(blank=True, null=True, verbose_name='强赎触发价'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_pe_ttm_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='正股TTM PE'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='ytm_before_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='到期税前收益'),
        ),
    ]
