# Generated by Django 5.1.2 on 2025-01-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0031_alter_bonddata_convertible_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonddata',
            name='is_risk_excluded',
            field=models.BooleanField(default=False, null=True, verbose_name='手动排除'),
        ),
    ]
