# Generated by Django 5.1.2 on 2025-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0032_alter_bonddata_is_risk_excluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonddata',
            name='is_risk_excluded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='手动排除'),
        ),
    ]
