# Generated by Django 5.1.2 on 2025-01-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0033_alter_bonddata_is_risk_excluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonddata',
            name='bond_rating',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='债券评级'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='convertible_price',
            field=models.FloatField(blank=True, null=True, verbose_name='转股价'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='convertible_value',
            field=models.FloatField(blank=True, null=True, verbose_name='转股价值'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='double_low',
            field=models.FloatField(blank=True, null=True, verbose_name='双低'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='issue_size',
            field=models.FloatField(blank=True, null=True, verbose_name='发行规模'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='listing_date',
            field=models.DateField(blank=True, null=True, verbose_name='上市时间'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='maturity_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='premium_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='转股溢价率'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='remaining_size',
            field=models.FloatField(blank=True, null=True, verbose_name='剩余规模'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='正股代码'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_industry_pb_ratio_median',
            field=models.FloatField(blank=True, null=True, verbose_name='行业中位数PB'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_industry_pe_ttm_ratio_median',
            field=models.FloatField(blank=True, null=True, verbose_name='行业中位数TTM PE'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='正股名称'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_pb',
            field=models.FloatField(blank=True, null=True, verbose_name='正股PB'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='stock_price',
            field=models.FloatField(blank=True, null=True, verbose_name='正股价'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='subscription_announcement_date',
            field=models.DateField(blank=True, null=True, verbose_name='中签号发布日'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='subscription_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='申购代码'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='subscription_date',
            field=models.DateField(blank=True, null=True, verbose_name='申购日期'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='subscription_per_share',
            field=models.FloatField(blank=True, null=True, verbose_name='原股东配售-每股配售额'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='subscription_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='中签率'),
        ),
        migrations.AlterField(
            model_name='bonddata',
            name='subscription_record_date',
            field=models.DateField(blank=True, null=True, verbose_name='原股东配售-股权登记日'),
        ),
    ]
