# Generated by Django 5.1.2 on 2025-08-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_100UpPlan', '0034_alter_bonddata_bond_rating_alter_bonddata_close_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonddata',
            options={'verbose_name': '可转债池', 'verbose_name_plural': '可转债池'},
        ),
        migrations.CreateModel(
            name='StockHistoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('code', models.CharField(max_length=50, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('period', models.CharField(default='monthly', max_length=20, verbose_name='周期')),
                ('adjust', models.CharField(default='qfq', max_length=10, verbose_name='复权类型')),
            ],
            options={
                'verbose_name': '股票历史数据',
                'verbose_name_plural': '股票历史数据',
                'db_table': 'market_stock_history_data',
                'indexes': [models.Index(fields=['code', 'period', 'adjust'], name='market_stoc_code_20c1a7_idx'), models.Index(fields=['date'], name='market_stoc_date_d55702_idx')],
                'unique_together': {('date', 'code', 'period', 'adjust')},
            },
        ),
    ]
